import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthProvider>
            <Navbar/>
            {children}
            <Toaster
              toastOptions={{
                classNames: {
                success: "!bg-green-500 !text-white !border-green-600",
                error: "!bg-red-500 !text-white !border-red-600",
                info: "!bg-blue-500 !text-white !border-blue-600",
                }
              }}
            />
          </AuthProvider>
          
        </body>
    </html>
  );
}
